name: Bloody Rose MD Runner

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # v3 වෙනුවට v4 දැම්මා

      - name: Setup Node.js
        uses: actions/setup-node@v4 # v3 වෙනුවට v4 දැම්මා
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Start Bloody Rose
        env:
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        run: node index.js
